<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="lidar_length" value="0.038"/>
    <xacro:property name="lidar_width" value="0.038"/>
    <xacro:property name="lidar_height" value="0.02"/>
    <xacro:property name="lidar_top_height" value="0.013"/>
    
    <link name="lidar_link">
        <visual>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
            <material name="black"/>            
        </visual>
        <collision>
            <geometry>
                <box size="${lidar_length} ${lidar_width} ${lidar_height}"/>
            </geometry>
        </collision>
        <!-- Inertia-->
         <xacro:box_inertia m="0.05" x="${lidar_length}" y="${lidar_width}" z="${lidar_height}"
            o_xyz="0 0 0" o_rpy="0 0 0"/>
    </link>

    <link name="lidar_top_link">
        <visual>
            <geometry>
                <cylinder radius="${lidar_length/2}" length="${lidar_top_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${lidar_length/2}" length="${lidar_top_height}"/>
            </geometry>
        </collision>
        <xacro:cylinder_inertia m="0.05" r="${lidar_length/2}" l="${lidar_top_height}"
        o_xyz="0 0 0" o_rpy="0 0 0"/>    
    </link>

      <!-- Scan output link for proper TF -->
      <link name="lidar_scan_link"/>
    
    <joint name="base_lidar_joint" type="fixed">
        <parent link="top_chassis_link"/>
        <child link="lidar_link"/>
        <origin xyz="0 0 ${-base_height+(-lidar_height/2)}" rpy=" 0 0 0"/>
    </joint>

    <joint name="lidar_top_joint" type="fixed">
        <parent link="lidar_link"/>
        <child link="lidar_top_link"/>
        <origin xyz="0 0 ${-lidar_height + (lidar_top_height/2)}" rpy="0 0 0"/>
    </joint>


    <joint name="lidar_scan_joint" type="fixed">
        <parent link="lidar_link"/>
        <child link="lidar_scan_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>


    <gazebo reference="lidar_scan_link">
        <sensor name="laser" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <always_on>true</always_on>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <topic>scan</topic>
            <gz_frame_id>laser_frame</gz_frame_id>
            <lidar>
               <scan>
                  <horizontal>
                  <samples>360</samples>
                  <min_angle>-3.14</min_angle>
                  <max_angle>3.14</max_angle>
                  </horizontal>
               </scan>
               <range>
                  <min>0.02</min>
                  <max>12</max>
               </range>
            </lidar>
         </sensor>
    </gazebo>

    
</robot>