<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org.wiki/xacro">

    <xacro:property name="scale" value="0.001"/>
    <xacro:property name="scalex" value="10"/>



    <xacro:property name="base_length" value="${2.0 / scalex}"/>
    <xacro:property name="base_width" value="${0.90 / scalex}"/>
    <xacro:property name="base_height" value="${0.03 / scalex}"/>

    <xacro:property name="wheel_radius" value="${0.335 / scalex}"/>
    <xacro:property name="wheel_length" value="${0.26 / scalex}"/>


    <xacro:property name="arm_connect_width" value="${0.448 / scalex}"/>
    <xacro:property name="arm_connect_length" value="${0.55 / scalex }"/>
    <xacro:property name="arm_connect_height" value="${0.35 / scalex}"/>

    <xacro:property name="wheel_joint_width" value="${0.8 / scalex}"/>
    <xacro:property name="wheel_joint_length" value="${0.3374 / scalex}"/>
    <xacro:property name="wheel_joint_height" value="${0.05 / scalex}"/>

    <xacro:property name="o_wheel_joint_width" value="${0.8 / scalex}"/>
    <xacro:property name="o_wheel_joint_length" value="${0.42 / scalex}"/>
    <xacro:property name="o_wheel_joint_height" value="${0.43 / scalex}"/>

    <xacro:property name="spacer_radius" value="${0.03 / scalex}"/>
    <xacro:property name="spacer_height" value="${0.50 / scalex}"/>




    <link name="base_footprint"/>


    <link name="base_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find wayfarer_description)/meshes/wayfarer/base_link.stl" scale="${scale} ${scale} ${scale}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0"/>
            <material name="green"/>
        </visual>

        <collision>
            <geometry>
                <mesh filename="package://wayfarer_description/meshes/wayfarer/base_link.stl" scale="${scale} ${scale} ${scale}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="1.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                            o_xyz="0 0 ${base_height}" o_rpy="0 0 ${pi/2}"/>
    </link>

    <link name="top_chassis_link">
        <visual>
            <geometry>
                <mesh filename="file://$(find wayfarer_description)/meshes/wayfarer/top_chassis.stl" scale="${scale} ${scale} ${scale}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="green"/>
        </visual>

        <collision>
            <geometry>
                <mesh filename="package://wayfarer_description/meshes/wayfarer/top_chassis.stl" scale="${scale} ${scale} ${scale}"/>
            </geometry>
            <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
        </collision>

        <xacro:box_inertia m="1.0" x="${base_length}" y="${base_width}" z="${base_height}" 
                            o_xyz="0 0 ${base_height}" o_rpy="0 0 ${pi/2}"/>
    </link>


    <xacro:arm_connect_link prefix="front"/>
    <xacro:arm_connect_link prefix="back"/>

    <xacro:wheel_joint_link prefix="front_right"/>
    <xacro:wheel_joint_link prefix="o_front_right"/>

    <xacro:wheel_joint_link prefix="front_left"/>
    <xacro:wheel_joint_link prefix="o_front_left"/>

    <xacro:wheel_joint_link prefix="back_right"/>
    <xacro:wheel_joint_link prefix="o_back_right"/>

    <xacro:wheel_joint_link prefix="back_left"/>
    <xacro:wheel_joint_link prefix="o_back_left"/>

    <xacro:wheel_link prefix="front_r"/>
    <xacro:wheel_link prefix="front_l"/>
    <xacro:wheel_link prefix="back_r"/>
    <xacro:wheel_link prefix="back_l"/>

    <xacro:spacer prefix="fr"/>
    <xacro:spacer prefix="fl"/>
    <xacro:spacer prefix="br"/>
    <xacro:spacer prefix="bl"/>




    <joint name="base_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${arm_connect_height + (wheel_joint_length/2) + (wheel_radius / 2)}" rpy="0 0 ${-pi/2}"/>
    </joint>

    <joint name="top_chassis" type="fixed">
        <parent link="base_link"/>
        <child link="top_chassis_link"/>
        <origin xyz="0 0 ${spacer_height + (base_height*2)}" rpy="${pi} 0 0"/>
    </joint>

    <!-- Base link to arm connect links -->
    <joint name="base_front_arm_connect_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_arm_connect_link"/>
        <origin xyz="0 ${base_length/4 - (arm_connect_length/2)} ${-arm_connect_height/2.0 - (base_height/2)}" rpy="${pi} 0 0"/>
    </joint>

    <joint name="base_back_arm_connect_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_arm_connect_link"/>
        <origin xyz="0 ${-base_length/4 - (arm_connect_length/2)} ${-arm_connect_height/2.0 - (base_height/2)}" rpy="${pi} 0 0"/>
    </joint>

    <!-- Wheel joints links -->
    <joint name="arm_connect_front_right_wheel_joint" type="fixed">
        <parent link="front_arm_connect_link"/>
        <child link="front_right_wheel_joint_link"/>
        <origin xyz="${-0.51 / scalex} ${-0.09/ scalex} ${0.18/ scalex}" rpy="${-pi/2} 0 0.0"/> 
    </joint>

    <joint name="arm_connect_front_left_wheel_joint" type="fixed">
        <parent link="front_arm_connect_link"/>
        <child link="front_left_wheel_joint_link"/>
        <origin xyz="${0.51/ scalex} ${-0.04/ scalex} ${0.18/ scalex}" rpy="${pi/2} ${pi} 0.0"/> 
    </joint>

    <joint name="arm_connect_back_right_wheel_joint" type="fixed">
        <parent link="back_arm_connect_link"/>
        <child link="back_right_wheel_joint_link"/>
        <origin xyz="${-0.51 / scalex} -${0.09 / scalex} ${0.18 / scalex}" rpy="${-pi/2} 0 0.0"/> 
    </joint>

    <joint name="arm_connect_back_left_wheel_joint" type="fixed">
        <parent link="back_arm_connect_link"/>
        <child link="back_left_wheel_joint_link"/>
        <origin xyz="${0.51 / scalex} ${-0.04 / scalex} ${0.18 / scalex}" rpy="${pi/2} ${pi} 0.0"/> 
    </joint>

    <joint name="arm_connect_o_front_right_wheel_joint" type="fixed">
        <parent link="front_arm_connect_link"/>
        <child link="o_front_right_wheel_joint_link"/>
        <origin xyz="${-0.51 / scalex} ${-0.45 / scalex} ${0.18 / scalex}" rpy="${pi/2} ${pi} ${pi}"/> 
    </joint>

    <joint name="arm_connect_o_back_right_wheel_joint" type="fixed">
        <parent link="back_arm_connect_link"/>
        <child link="o_back_right_wheel_joint_link"/>
        <origin xyz="${-0.51 / scalex} ${-0.45 / scalex} ${0.18 / scalex}" rpy="${pi/2} ${pi} ${pi}"/> 
    </joint>

    <joint name="arm_connect_o_front_left_wheel_joint" type="fixed">
        <parent link="front_arm_connect_link"/>
        <child link="o_front_left_wheel_joint_link"/>
        <origin xyz="${0.51 / scalex} ${-0.40 / scalex} ${0.18 / scalex}" rpy="${pi/2} ${pi} 0"/> 
    </joint>

    <joint name="arm_connect_o_back_left_wheel_joint" type="fixed">
        <parent link="back_arm_connect_link"/>
        <child link="o_back_left_wheel_joint_link"/>
        <origin xyz="${0.51 / scalex} ${-0.40 / scalex} ${0.18 / scalex}" rpy="${pi/2} ${pi} 0"/> 
    </joint>


    <!-- Wheels -->
    <joint name="front_r_arm_wheel_joint" type="continuous">
        <parent link="front_left_wheel_joint_link"/>
        <child link="front_r_wheel_link"/>
        <origin xyz="${-wheel_joint_width/2 + (-wheel_length/3.5)} 0.0 ${wheel_radius /2 + (0.05 / scalex)}" rpy="0 0 ${pi/2} "/>
        <axis xyz="0.0 -1.0 0.0"/>
    </joint>

    <joint name="front_l_arm_wheel_joint" type="continuous">
        <parent link="front_right_wheel_joint_link"/>
        <child link="front_l_wheel_link"/>
        <origin xyz="${-wheel_joint_width/2 + (-wheel_length/3.5)} 0.0 ${-wheel_radius /2 + (0.05 / scalex)}" rpy="0 0 ${pi/2} "/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <joint name="back_r_arm_wheel_joint" type="continuous">
        <parent link="back_left_wheel_joint_link"/>
        <child link="back_r_wheel_link"/>
        <origin xyz="${-wheel_joint_width/2 + (-wheel_length/3.5)} 0.0 ${wheel_radius /2 + (0.05 /scalex)}" rpy="0 0 ${pi/2} "/>
        <axis xyz="0.0 -1.0 0.0"/>
    </joint>

    <joint name="back_l_arm_wheel_joint" type="continuous">
        <parent link="back_right_wheel_joint_link"/>
        <child link="back_l_wheel_link"/>
        <origin xyz="${-wheel_joint_width/2 + (-wheel_length/3.5)} 0.0 ${-wheel_radius /2 + (0.05 / scalex)}" rpy="0 0 ${pi/2} "/>
        <axis xyz="0.0 1.0 0.0"/>
    </joint>

    <!-- Spacers -->
    <joint name="fr_spacer_joint" type="fixed">
        <parent link="base_link"/>
        <child link="fr_spacer"/>
        <origin xyz="${base_width/2.5} ${base_length / 2.15} ${(wheel_radius/2)+(wheel_joint_height/2)+(arm_connect_height)} " rpy="${pi/2} 0 0"/> 
    </joint>

    <joint name="fl_spacer_joint" type="fixed">
        <parent link="base_link"/>
        <child link="fl_spacer"/>
        <origin xyz="${-base_width/2.5} ${base_length / 2.15} ${(wheel_radius/2)+(wheel_joint_height/2)+(arm_connect_height)} " rpy="${pi/2} 0 0"/> 
    </joint>

    <joint name="br_spacer_joint" type="fixed">
        <parent link="base_link"/>
        <child link="br_spacer"/>
        <origin xyz="${base_width/2.5} ${-base_length / 2.15} ${(wheel_radius/2)+(wheel_joint_height/2)+(arm_connect_height)} " rpy="${pi/2} 0 0"/> 
    </joint>

    <joint name="bl_spacer_joint" type="fixed">
        <parent link="base_link"/>
        <child link="bl_spacer"/>
        <origin xyz="${-base_width/2.5} ${-base_length / 2.15} ${(wheel_radius/2)+(wheel_joint_height/2)+(arm_connect_height)} " rpy="${pi/2} 0 0"/> 
    </joint>


</robot>